### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/account-viewer#11]

**Comment by irisli** [comment]
I have implemented the front end of the transaction history (https://github.com/stellar/account-viewer/tree/payment-history). An interesting observation here is that this is actually a `Payments History` rather than a `Transaction History` since it is meant to show "Payments" which is a subset of a transaction.

## Responsiveness

Right now, it is only available in desktop table format. Users on smaller screens will have to horizontally scroll to see all the information.

## Screen shots

![screen shot 2015-12-02 at 1 27 54 pm](https://cloud.githubusercontent.com/assets/5728307/11544931/6e95e3e4-98f9-11e5-823d-6fd8f88224ef.png)
<img width="487" alt="screen shot 2015-12-02 at 1 34 19 pm" src="https://cloud.githubusercontent.com/assets/5728307/11544935/6fdce41e-98f9-11e5-8e57-1c2f9e04a51d.png">

## "Business requirements"

The "transactions" displayed here are simply just all the payments involving the user's account.

In this simple version, there is no pagination. Instead, we should just Horizon ask for the past 100 payments.

### Payment limit

If we received 100 payments from Horizon (meaning the user has more than 100 payments), show this alert box.
![image](https://cloud.githubusercontent.com/assets/5728307/11545311/9057d4ea-98fb-11e5-9edd-e078a4c8d6c5.png)

### Date (currently blocked)

We simply format the `created_at` from Horizon using the AngularJS date filter:

```
{{'2015-08-06T18:20:50Z' | date:"MMMM d, y H:mm:ss Z"}}
```

I chose to absolute time instead of relative time since it is often more useful than a relative date.

As of right now, Horizon does not show the date in the operations resource.
It should be added to Horizon soon though. https://github.com/stellar/horizon/issues/206

### Account ID

Show the account ID of the other party participating in this transaction.
I think that in all operations, there are two parties: sender and receiver.

### Amount

#### Positive and negative

If the amount is negative, the amount should appear in red. Always show the plus or minus symbol.

#### Asset code

If it is a native asset, just show `XLM`.
If it is a non-native asset type, show the asset code. We don't show the issuer as of right now but if it becomes more important later, we can add it in.

### Memo

#### Type

Always show the memo type. If no memo, show `NONE`.

#### Contents

Show the memo body in the relevant format.

For hashes, show the hash.

### Operation ID

This section helps a user get more in depth details about that operation. The operation ID should be a link to the operation (from `_links.self`).

**Comment by irisli** [comment]
The date portion soft-blocked by horizon https://github.com/stellar/horizon/issues/206

The rest can be implemented now.

**Comment by jessica-collier** [comment]
Edit to alert: 

This tool shows up to 100 most recent payments. To view more, use the Horizon API.

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/account-viewer/commit/d9c0d96b3926ef125a29d570cddec187b9dc2af1
