### ISSUE TITLE
Transactions history visibility on some resolutions

### ISSUE THREAD

**Issue by bartekn** [stellar/account-viewer#23]
On medium screens (ex. 1440x900) app header and send widget fills the full screen size:
![stellar account viewer](https://cloud.githubusercontent.com/assets/464938/11628725/d18ba9fe-9cf3-11e5-92fe-658b7a7ae16c.png)
Some users may not notice transactions history (some browsers/systems don't show scrolls).

**Comment by irisli** [comment]
This is an inevitable part of the fold but I think most users know how to scroll. Still, there can be things to help the user.

## Below fold indicator [`branch: below-fold-indicator`](https://github.com/stellar/account-viewer/tree/below-fold-indicator)

![image](https://cloud.githubusercontent.com/assets/5728307/11636869/3155ce80-9cd3-11e5-8cfc-49b89127ebdf.png)

We can have this indicator to show that there is more under the fold.
- Once the `Transaction History` is visible, then the indicator goes away.
- When the user clicks it, the screen will scroll down to the correct place.
- Not visible in narrow screens since they will have to scroll a lot anyways (see the other improvement below)

## Scroll after transaction success

After the user successfully sends a transaction, we scroll them to the Transaction History section.
- Helpful for users on narrow screens
- Highlight the just-sent transaction for a few seconds

**Comment by vcarl** [comment]
Closing this as outdated
