### ISSUE TITLE
Is "aggressive" in the amount of requests made to horizon.

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/account-viewer#8]
Looks like it is requesting the account balance as fast as it can. It should use the streaming end point to get the account balance

**Comment by bartekn** [comment]
I can work on small improvements to lower the number of balance request but it still won't solve the problem. For accounts with large number of payment operations horizon will stream all payments from the account creation. Closing https://github.com/stellar/horizon/issues/112 will help solving this issue.

**Comment by nullstyle** [comment]
@bartekn, I don't understand why you must stream all payments from the beginning of time in the basic client, could you explain it further?

It seems like you should be able to simply load the last page of payments for a user using `order=desc` and be done with it.

**Comment by bartekn** [comment]
It's because of the way [`interstellar-network.AccountObservable`](https://github.com/stellar/interstellar-network/blob/master/services/account-observable.service.es6) service works right now. It exists to support one common way for all widgets to get information about account balance and payments.

I can fix it in basic-client by streaming `/accounts/{address}` endpoint but we need to fix  stellar/horizon#112 in the future to stream only latest `/payments` objects.

**Comment by nullstyle** [comment]
I still do not understand _why_ we must start from the beginning of time.  Ostensibly, `registerPaymentListener` is only interested in payments that occur after the initial pageload (i.e. payments that occur while the user is using the client).  Nothing about that need _requires_ us to have https://github.com/stellar/horizon/issues/112 fixed.  Instead:
1.  On page load, load the last page of payments for the account `GET /accounts/:address/payments?order=desc`
2.  Save the `paging_token` of the first payment in the result (i.e. the latest payment)
3.  Start the stream with the `cursor` set to the value saved in step 2: `GET /accounts/:address/payments?order=asc&cursor=:paging_token`

If the above does not work, could you please detail why?

**Comment by nullstyle** [comment]
I would argue in fact, that the design above is better than providing a `latest` cursor because it guarantees that no transactions will be missed (i.e. if a transaction closes in between 1 and 3 in the above design)

**Comment by bartekn** [comment]
Yes, I think you're right. For basic-client I'm streaming `/accounts/{address}` from 578a5fb since we're only displaying balance and no payments history. But I can image situations when `latest` cursor would be helpful (ex. visual notification system in which missing a single payment is not a big deal).

**Comment by nullstyle** [comment]
Alright, sweet.  It seems like we're on the same page then.  FYI, I'll be adding the `latest` cursor support this orbit, probably sometime next week.

**Comment by bartekn** [comment]
Great! :+1:
